### ISSUE TITLE
Models with custom ID

### ISSUE THREAD

**Issue by glennwilton** [orlyapps/nova-belongsto-depend#1]
Hi

My Models have custom id fields, so any reference to field->id fails, I needed to make a few changes

**NovaBelongsToDepend.php** 
Line 86 Change to `$this->dependKey = $foreign->getKey();`

**FormField.vue**
Line 56 Change to `dependKey:  dependsOnValue.value[dependsOnValue.field.modelKeyName]`
Line 97 Change to `formData.append(this.field.attribute, this.value[this.field.modelKeyName] || "");`

**Comment by orlyapps** [comment]
Hello,

can you make a pull request?

Thanks 👍

**Comment by glennwilton** [comment]
Sure, never done one, so always a first time for everything :-)

**Comment by orlyapps** [comment]
https://github.com/orlyapps/nova-belongsto-depend/commit/85e9a1e90c2b07c3a55c698508990d3f7eb923e9 should fix your problem.
Can you try it with this version?

**Comment by glennwilton** [comment]
Just tried the latest version, CustomID problem fixed.
