### ISSUE TITLE
Panel Not Imported

### ISSUE THREAD

**Issue by ConnorVG** [orlyapps/nova-belongsto-depend#12]
The current reason for panels not working is that the `Panel` class isn't imported for use in the aggregation:
https://github.com/orlyapps/nova-belongsto-depend/blob/62820d0cdd615e6a063cc0d0f412a6ad3e17dd75/src/Http/Controllers/FieldController.php

**Comment by orlyapps** [comment]
Oh, Thanks for the issue. We will fix it asap.
