### ISSUE TITLE
nova-belongsto-depend not working when used inside tabs

### ISSUE THREAD

**Issue by lvdhoorn** [orlyapps/nova-belongsto-depend#14]
I was trying to make a belongs to field working with a dependency.

I keep getting this error:
**Can not find the Field "countryweek" in the Model "App\Nova\Expense"**

The code was like this:
`
new NovaTab('General information', [
                NovaBelongsToDepend::make('Week')
                    ->options(\App\Week::all()),
                NovaBelongsToDepend::make('countryweek')
                    ->optionsResolve(function ($weeks) {
                        return 'hello';
                    })
                    ->dependsOn('Week')
                ,
            ]),
`

Then at some point i figured out that the fact that the field is inside a NovaTab that the nova-belongsto-depend class can't find the field. It would be nice if it is possible to use this solutions inside the NovaTab module.

**Comment by orlyapps** [comment]
Hello, thanks for the issue. I will look into it :)

**Comment by emilianotisato** [comment]
Hello @orlyapps any update on this?

Thanks by the way!!

**Comment by orlyapps** [comment]
this should be fixed now.
