### ISSUE TITLE
Options not displayed on short page

### ISSUE THREAD

**Issue by obeone** [orlyapps/nova-belongsto-depend#20]
Nova use a overflow hidden style, if select is displayed at the end of a page, some items cannot be displayed (unable to scroll to).

![image](https://user-images.githubusercontent.com/2248719/48008336-c1ffd100-e119-11e8-936a-17844009a88f.png)

**Comment by orlyapps** [comment]
Currently i have no idea how to fix this :(

**Comment by lvdhoorn** [comment]
I have the same problem. The "temp fix" for me was to put the select on top of the form. If you have a sort form that is not really a solution.

**Comment by orlyapps** [comment]
fixed with da287a0c057963fd456e82c40c4f6fd755596f75
