### ISSUE TITLE
Making nova-belongsto-depend Work With Nova Spatie Translatable

### ISSUE THREAD

**Issue by issour** [orlyapps/nova-belongsto-depend#23]
Translatable::make([
    NovaBelongsToDepend::make('Country', 'country')
                ->options(\App\Country::all())
                ->rules('required'),

]),

<img width="768" alt="capture d ecran 2018-11-13 a 23 02 41" src="https://user-images.githubusercontent.com/44650070/48448977-a12e2000-e798-11e8-9286-6b967fdb9cc7.png">

**Comment by cord** [comment]
same here!

**Comment by rybakk** [comment]
you can work around the problem by generating a custom object array like this: 
`
$typesArray = [];
foreach (EntityType::all() as $entityType) {
            $type = new \stdClass();
            $type->id = $entityType->id;
            $type->name = $entityType->name;
            $typesArray[] = $type;
}
NovaBelongsToDepend::make(__('Entity Type'), 'type')->options($typesArray)
`

**Comment by shahabzebare** [comment]
public function getNameAttribute()
    {
        return $this->getTranslations('name')[app()->getLocale()];
    }
