### ISSUE TITLE
Collision with package arsenaltech/nova-tab

### ISSUE THREAD

**Issue by carloscgo** [orlyapps/nova-belongsto-depend#25]
I have a collision with use package arsenaltech/nova-tab, the field province no found.
But when remove this tab the field work perfect.

![image](https://user-images.githubusercontent.com/693763/48588283-7a8cf800-e904-11e8-9bbc-7df22c789b23.png)

**Comment by CasperLaiTW** [comment]
which version you used in nova-tab and nova-belongsto-depend?

I tried in nova-tab(0.2.0) and nova-belongsto-depend(master) and working well.

can you provide code and specific description?

**Comment by emilianotisato** [comment]
Same issue here:
        "arsenaltech/nova-tab": "^0.2.0",
        "orlyapps/nova-belongsto-depend": "^0.0.6",

I don't understand why

**Comment by CasperLaiTW** [comment]
Can you provide fields method code in the resource?

**Comment by emilianotisato** [comment]
Hello @CasperLaiTW, this is what I have inside the fields() method in the resource class:

`           BelongsTo::make('Operation')->rules('required'),
            BelongsTo::make('Currency')->rules('required'),
            Number::make('Amount')->min(1)->max(999999999999)->step(1)->rules('required'),

            NovaBelongsToDepend::make('Zone')->options(\App\Zone::all())->onlyOnForms(),
            NovaBelongsToDepend::make('Area')->optionsResolve(function ($zone) {
                return $zone->areas()->get(['id','name']);
            })->dependsOn('Zone')->rules('required')->hideFromIndex(),
`

**Comment by carloscgo** [comment]
My code is used nova-tab:

```
            new NovaTab('Address Information', [
                NovaBelongsToDepend::make('Country')
                    ->options(\App\Models\Countries::all())
                    ->rules('required'),

                NovaBelongsToDepend::make('Province')
                    ->optionsResolve(function ($country) {
                        return $country->Provinces()->select(['id', 'exonimo_en AS name'])->get(['id', 'name']);
                    })
                    ->dependsOn('Country')
                    ->rules('required'),

                Text::make('City')
                    ->hideFromIndex()
                    ->rules('required', 'max:45'),

                Text::make('Zip Code', 'zip_code')
                    ->hideFromIndex()
                    ->rules('required', 'max:10'),

                Place::make('Address')
                    ->rules('required')
                    ->hideFromIndex(),
            ]),
```

**Comment by CasperLaiTW** [comment]
Hi @emilianotisato @carloscgo 

I fixed from my local, so I didn't get the issue, and now I create PR for the issue. 

you can use my fork

https://github.com/CasperLaiTW/nova-belongsto-depend

**Comment by CasperLaiTW** [comment]
You can update composer.json

in composer.json
```
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "repositories": [
        {
            "type": "vcs",
            "url": "git@github.com:CasperLaiTW/nova-belongsto-depend.git"
        },
    ],
    "require": {
        "orlyapps/nova-belongsto-depend": "dev-master",
    }
}
```
