### ISSUE TITLE
Field not automatically filled in when creating from related resource

### ISSUE THREAD

**Issue by PhilippeDirx** [orlyapps/nova-belongsto-depend#28]
I have 2 resources:

1) Product
2) Stock

Product has a **HasMany** relation on Stock
Stock has a **NovaBelongsToDepend** on Product
When creating Stock **from** a Product detail page 
*(viaResource=products&viaResourceId=1&viaRelationship=stocks)*
 the relation **does not get auto filled**.

**Comment by mydnic** [comment]
I have the same issue. No solution yet ?

**Comment by PhilippeDirx** [comment]
Appearently not, package seems abandoned...
I'll try and fix this in a fork!

**Comment by orlyapps** [comment]
Hello, you can submit a pull requests and i will merge it :)
