### ISSUE TITLE
titleKey

### ISSUE THREAD

**Issue by ardyn** [orlyapps/nova-belongsto-depend#3]
The following line
`$this->titleKey = Nova::resourceForKey(str_plural($this->attribute))::$title;`
is failing when the model has a non-standard BelongsTo relationship method name.

We need to be able to set $this->titleKey manually.

I passed in a fourth argument to make method and then changed code to
`$this->titleKey = $titleKey ?? Nova::resourceForKey(str_plural($this->attribute))::$title;`

**Comment by orlyapps** [comment]
Hello,

thanks for your bug report. This commit https://github.com/orlyapps/nova-belongsto-depend/commit/b3e5619cb7b1c513fe930cad33c7d80e3f1bc482 should fix your problem.

I have also created a demo project:
https://github.com/orlyapps/laravel-nova-demo

Can you try it again?

**Comment by ardyn** [comment]
That works.

Ideally it should use the resources title() method, but that requires the
model to be instantiated and not called statically.

**Comment by glennwilton** [comment]
Just tried the latest version, TitleKey fix also worked for me. Ok to close
