### ISSUE TITLE
Reduce the amount of unnecessary data sent 

### ISSUE THREAD

**Issue by glennwilton** [orlyapps/nova-belongsto-depend#5]
In the documentation the options() and optionsResolve() send the full records as JSON to the frontend.

It would be better to filter these by the modelKeyName and valueKey so only send whats required.

Alternatively change the documentation as below to only get the required fields.

```
->optionsResolve(function ($customer) {
     return $customer->sites()->get(['siteID', 'siteDescription']);
})
```

**Comment by orlyapps** [comment]
Thanks 👍 
I have decided you change the README.
