### ISSUE TITLE
Cannot translate as described in readme

### ISSUE THREAD

**Issue by PatricNox** [orlyapps/nova-belongsto-depend#50]
Readme says this:

> The following strings are translatable (add then in your language file located in resources/lan/vendor/nova/*.json).
> 
> 'Oops! No elements found. Consider changing the search query.'
> 'List is empty'
> 'Select'
> 'Press enter to select'
> 'Selected'
> 'Press enter to remove'

however, after doing just that for 'Press enter to remove', nothing changed. 
Tried to clear cache, no good.

Nova  v2.3.1
Laravel Framework 5.8.31

**Comment by XternalSoft** [comment]
Hello @PatricNox ,

I just tried, and it's working
Nova v2.5
Laravel 5.8

In resources/lang/vendor/nova/fr.json

**Comment by PatricNox** [comment]
Hey @XternalSoft !

i've put the translation strings in resources/lang/vendor/nova/en.json, while EN is the locale, and then refresh the site without any change.

Tried to run artisan cache:clear and config:clear to no avail as well. 
Am I missing something obvious here?

**Comment by Paulsky** [comment]
@PatricNox did you find a fix for this issue?

**Comment by Paulsky** [comment]
Shouldn't the translation files be in resources/lang/vendor/nova-belongsto-depend/*.json? Like most packages? This is a cleaner way to manage and maintain the translation in my opinion.

**Comment by PatricNox** [comment]
@Paulsky  Yes, that's what I had to do as well but you're very correct about the package level to be the "correct" way.
