### ISSUE TITLE
How to set the name of the relationship column

### ISSUE THREAD

**Issue by derrickkorku** [orlyapps/nova-belongsto-depend#64]
I am trying to set a name for a relationship column, example like this:

Argument 1. Name to display (e.g. Age Group)
Argument 2. Name of the relationship as used in the model (e.g. SchoolAgeGroup)
Argument 3. The Nova Resource (e.g. App\Nova\SchoolAgeGroup)

NovaBelongsToDepend::make('Age Group', 'SchoolAgeGroup', 'App\Nova\SchoolAgeGroup')

Is there are a way to do this?

**Comment by thaifani** [comment]
we want this too

**Comment by marcusgabler** [comment]
Hello, you already got the solution in front of you, the code snippet your wrote, works:

**NovaBelongsToDepend::make('Age Group', 'SchoolAgeGroup', 'App\Nova\SchoolAgeGroup')**

**Comment by orlyapps** [comment]
Thanks @marcusgabler
