### ISSUE TITLE
API Request Increment and Looping After Edit Multiple Times

### ISSUE THREAD

**Issue by irfanhkm** [orlyapps/nova-belongsto-depend#72]
<img width="1215" alt="Screen Shot 2020-08-29 at 2 34 07 PM" src="https://user-images.githubusercontent.com/30617181/91631567-b5422080-ea04-11ea-99da-b0d4fb94e3d5.png">
<img width="1552" alt="Screen Shot 2020-08-29 at 2 34 22 PM" src="https://user-images.githubusercontent.com/30617181/91631569-bc692e80-ea04-11ea-869e-3fc1f6a2fabd.png">
<img width="1552" alt="Screen Shot 2020-08-29 at 2 34 38 PM" src="https://user-images.githubusercontent.com/30617181/91631576-c854f080-ea04-11ea-941a-c17159d6d2c3.png">

Step Reproduce :
1 Create resource
2 Open Detail
3 Update The Data
4. Repeat step 2 & 3

after 4 or 5 steps the forms will be laggy and show up an unnecessary validation that shouldn't appear when submitting again.

<img width="1145" alt="Screen Shot 2020-08-29 at 2 38 59 PM" src="https://user-images.githubusercontent.com/30617181/91631647-621c9d80-ea05-11ea-8b30-ec73b17414e8.png">

**Comment by orlyapps** [comment]
this should be fixed in the latest release. Re-open when it still occures
